/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    admissions: Admission;
    media: Media;
    'content-sections': ContentSection;
    editorial: Editorial;
    documents: Document;
    forms: Form;
    'form-submissions': FormSubmission;
    'notification-deliveries': NotificationDelivery;
    'audit-records': AuditRecord;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    admissions: AdmissionsSelect<false> | AdmissionsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'content-sections': ContentSectionsSelect<false> | ContentSectionsSelect<true>;
    editorial: EditorialSelect<false> | EditorialSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'notification-deliveries': NotificationDeliveriesSelect<false> | NotificationDeliveriesSelect<true>;
    'audit-records': AuditRecordsSelect<false> | AuditRecordsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'website-settings': WebsiteSetting;
    'notification-settings': NotificationSetting;
  };
  globalsSelect: {
    'website-settings': WebsiteSettingsSelect<false> | WebsiteSettingsSelect<true>;
    'notification-settings': NotificationSettingsSelect<false> | NotificationSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Admins can manage Admin, Teacher, and Parent accounts. Principal accounts are managed by a Principal.
   */
  role: 'principal' | 'admin' | 'teacher' | 'parent' | 'staff';
  active: boolean;
  /**
   * Custom permissions apply to Teachers. Administrators and Principals retain full content access; Parents cannot enter the CMS.
   */
  contentAccess?: ('role' | 'custom') | null;
  /**
   * Applies across website sections, news, downloads, and Media Library. Editing without approval is limited to drafts.
   */
  contentPermissions?: ('edit' | 'remove' | 'approve')[] | null;
  assignedSections?: (number | ContentSection)[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-sections".
 */
export interface ContentSection {
  id: number;
  /**
   * Stable website placement. Create only one record for each key.
   */
  key: 'resources.school-calendar' | 'student-life.sports' | 'student-life.clubs' | 'site.contact';
  heading?: string | null;
  introduction?: string | null;
  calendar?: {
    academicYear?: string | null;
    termBreaks?:
      | {
          label: string;
          value: string;
          emphasis?: boolean | null;
          id?: string | null;
        }[]
      | null;
    assessments?:
      | {
          label: string;
          value: string;
          emphasis?: boolean | null;
          id?: string | null;
        }[]
      | null;
    gradeXMeetings?:
      | {
          label: string;
          value: string;
          emphasis?: boolean | null;
          id?: string | null;
        }[]
      | null;
    reportMeetings?:
      | {
          label: string;
          value: string;
          emphasis?: boolean | null;
          id?: string | null;
        }[]
      | null;
    specialDays?:
      | {
          label: string;
          value: string;
          emphasis?: boolean | null;
          id?: string | null;
        }[]
      | null;
    dailySchedule?:
      | {
          label: string;
          value: string;
          emphasis?: boolean | null;
          id?: string | null;
        }[]
      | null;
    publicHolidays?:
      | {
          label: string;
          value: string;
          emphasis?: boolean | null;
          id?: string | null;
        }[]
      | null;
    calendarDocument?: (number | null) | Document;
  };
  sports?: {
    philosophy?: string | null;
    coaching?: string | null;
    achievements?: string | null;
    disciplines?:
      | {
          name: string;
          id?: string | null;
        }[]
      | null;
    cards?:
      | {
          itemKey: string;
          title: string;
          description: string;
          image?: (number | null) | Media;
          legacyImagePath?: string | null;
          alt?: string | null;
          objectPosition?: ('center' | 'top' | 'bottom' | 'left' | 'right') | null;
          id?: string | null;
        }[]
      | null;
  };
  clubs?: {
    flagship?: {
      name?: string | null;
      tagline?: string | null;
      description?: string | null;
      image?: (number | null) | Media;
      legacyImagePath?: string | null;
      alt?: string | null;
    };
    cards?:
      | {
          itemKey: string;
          title: string;
          description: string;
          image?: (number | null) | Media;
          legacyImagePath?: string | null;
          alt?: string | null;
          objectPosition?: ('center' | 'top' | 'bottom' | 'left' | 'right') | null;
          id?: string | null;
        }[]
      | null;
  };
  contact?: {
    eyebrow?: string | null;
    description?: string | null;
    address?: string | null;
    phoneDisplay?: string | null;
    phoneHref?: string | null;
    admissionsEmail?: string | null;
    principalEmail?: string | null;
    mapEmbedUrl?: string | null;
    mapTitle?: string | null;
    visitTitle?: string | null;
    visitDescription?: string | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
  };
  publicationState: 'draft' | 'scheduled' | 'published' | 'expired' | 'archived';
  publishAt?: string | null;
  expiresAt?: string | null;
  publishedAt?: string | null;
  publicationActor?: (number | null) | User;
  publicationChangedAt?: string | null;
  createdBy?: (number | null) | User;
  assignedEditors?: (number | User)[] | null;
  migrationId?: string | null;
  migrationSource?: string | null;
  migrationFingerprint?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  title: string;
  type: 'circular' | 'holiday_list' | 'newsletter' | 'general_download' | 'mandatory_disclosure';
  category?: string | null;
  academicYear?: string | null;
  effectiveDate?: string | null;
  description?: string | null;
  issueNumber?: string | null;
  audience?: string | null;
  displayOrder: number;
  placements: ('downloads' | 'mandatory-disclosure' | 'school-calendar')[];
  sourceType: 'upload' | 'external';
  pdf?: (number | null) | Media;
  externalUrl?: string | null;
  legacyExternalUrl?: string | null;
  publicationState: 'draft' | 'scheduled' | 'published' | 'expired' | 'archived';
  publishAt?: string | null;
  expiresAt?: string | null;
  publishedAt?: string | null;
  publicationActor?: (number | null) | User;
  publicationChangedAt?: string | null;
  createdBy?: (number | null) | User;
  assignedEditors?: (number | User)[] | null;
  migrationId?: string | null;
  migrationSource?: string | null;
  migrationFingerprint?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Reusable image and PDF assets become available only after server-side verification.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  title: string;
  originalFilename?: string | null;
  category: string;
  alt?: string | null;
  /**
   * Decorative images are rendered with an empty alternative text attribute.
   */
  decorative?: boolean | null;
  caption?: string | null;
  uploadedBy?: (number | null) | User;
  uploadedAt?: string | null;
  verificationStatus?: ('pending' | 'verified' | 'failed') | null;
  /**
   * Automatic file-check result. Save a failed upload to retry verification.
   */
  verificationMessage?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admissions".
 */
export interface Admission {
  id: number;
  studentName: string;
  grade: string;
  dateOfBirth: string;
  gender: 'male' | 'female' | 'other';
  bloodGroup?: string | null;
  category?: string | null;
  /**
   * Aadhaar numbers are masked in collection lists.
   */
  aadharNo?: string | null;
  motherTongue?: string | null;
  previousSchool?: string | null;
  previousSchoolAddress?: string | null;
  board?: string | null;
  classLastStudied?: string | null;
  transferCertificateNo?: string | null;
  fatherName: string;
  fatherOccupation?: string | null;
  fatherQualification?: string | null;
  motherName: string;
  motherOccupation?: string | null;
  motherQualification?: string | null;
  contactNumber: string;
  alternatePhone?: string | null;
  parentEmail?: string | null;
  address: string;
  permanentAddress?: string | null;
  documentsEnclosed?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status: 'pending' | 'reviewed' | 'accepted' | 'rejected';
  referenceCode?: string | null;
  submittedAt?: string | null;
  statusChangedBy?: (number | null) | User;
  statusChangedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "editorial".
 */
export interface Editorial {
  id: number;
  kind: 'news' | 'event' | 'announcement';
  title: string;
  slug?: string | null;
  /**
   * Stable /news-events URL segment.
   */
  publicPathKey?: string | null;
  summary?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  message?: string | null;
  link?: string | null;
  displayOrder: number;
  priority?: number | null;
  /**
   * Latest News is the complete news list. Select “Show in homepage News & Events” to cherry-pick an item for the landing page.
   */
  placements: ('resource-news' | 'homepage-news' | 'resource-announcements' | 'header-ticker')[];
  category?: string | null;
  featured?: boolean | null;
  displayDate?: string | null;
  image?: (number | null) | Media;
  legacyImagePath?: string | null;
  startsAt?: string | null;
  endsAt?: string | null;
  location?: string | null;
  publicationState: 'draft' | 'scheduled' | 'published' | 'expired' | 'archived';
  publishAt?: string | null;
  expiresAt?: string | null;
  publishedAt?: string | null;
  publicationActor?: (number | null) | User;
  publicationChangedAt?: string | null;
  createdBy?: (number | null) | User;
  assignedEditors?: (number | User)[] | null;
  migrationId?: string | null;
  migrationSource?: string | null;
  migrationFingerprint?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  referenceCode?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Immutable notification attempts. Retries are stored as linked new attempts.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-deliveries".
 */
export interface NotificationDelivery {
  id: number;
  channel: 'email';
  sourceType: 'admission' | 'form_submission';
  source:
    | {
        relationTo: 'admissions';
        value: number | Admission;
      }
    | {
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      };
  status: 'pending' | 'sent' | 'failed' | 'disabled' | 'not_configured';
  attemptNumber: number;
  attemptedAt?: string | null;
  recipient?: string | null;
  providerMessageId?: string | null;
  errorCode?: string | null;
  errorMessage?: string | null;
  initiatedBy?: (number | null) | User;
  previousAttempt?: (number | null) | NotificationDelivery;
}
/**
 * Append-only security and workflow audit events.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-records".
 */
export interface AuditRecord {
  id: number;
  actorType: 'system' | 'user';
  actorId?: string | null;
  actorRole?: ('principal' | 'admin' | 'teacher' | 'parent') | null;
  action: string;
  targetCollection: string;
  targetId: string;
  occurredAt: string;
  outcome: 'success' | 'failure' | 'denied';
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'admissions';
        value: number | Admission;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'content-sections';
        value: number | ContentSection;
      } | null)
    | ({
        relationTo: 'editorial';
        value: number | Editorial;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'notification-deliveries';
        value: number | NotificationDelivery;
      } | null)
    | ({
        relationTo: 'audit-records';
        value: number | AuditRecord;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  active?: T;
  contentAccess?: T;
  contentPermissions?: T;
  assignedSections?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admissions_select".
 */
export interface AdmissionsSelect<T extends boolean = true> {
  studentName?: T;
  grade?: T;
  dateOfBirth?: T;
  gender?: T;
  bloodGroup?: T;
  category?: T;
  aadharNo?: T;
  motherTongue?: T;
  previousSchool?: T;
  previousSchoolAddress?: T;
  board?: T;
  classLastStudied?: T;
  transferCertificateNo?: T;
  fatherName?: T;
  fatherOccupation?: T;
  fatherQualification?: T;
  motherName?: T;
  motherOccupation?: T;
  motherQualification?: T;
  contactNumber?: T;
  alternatePhone?: T;
  parentEmail?: T;
  address?: T;
  permanentAddress?: T;
  documentsEnclosed?: T;
  status?: T;
  referenceCode?: T;
  submittedAt?: T;
  statusChangedBy?: T;
  statusChangedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  title?: T;
  originalFilename?: T;
  category?: T;
  alt?: T;
  decorative?: T;
  caption?: T;
  uploadedBy?: T;
  uploadedAt?: T;
  verificationStatus?: T;
  verificationMessage?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-sections_select".
 */
export interface ContentSectionsSelect<T extends boolean = true> {
  key?: T;
  heading?: T;
  introduction?: T;
  calendar?:
    | T
    | {
        academicYear?: T;
        termBreaks?:
          | T
          | {
              label?: T;
              value?: T;
              emphasis?: T;
              id?: T;
            };
        assessments?:
          | T
          | {
              label?: T;
              value?: T;
              emphasis?: T;
              id?: T;
            };
        gradeXMeetings?:
          | T
          | {
              label?: T;
              value?: T;
              emphasis?: T;
              id?: T;
            };
        reportMeetings?:
          | T
          | {
              label?: T;
              value?: T;
              emphasis?: T;
              id?: T;
            };
        specialDays?:
          | T
          | {
              label?: T;
              value?: T;
              emphasis?: T;
              id?: T;
            };
        dailySchedule?:
          | T
          | {
              label?: T;
              value?: T;
              emphasis?: T;
              id?: T;
            };
        publicHolidays?:
          | T
          | {
              label?: T;
              value?: T;
              emphasis?: T;
              id?: T;
            };
        calendarDocument?: T;
      };
  sports?:
    | T
    | {
        philosophy?: T;
        coaching?: T;
        achievements?: T;
        disciplines?:
          | T
          | {
              name?: T;
              id?: T;
            };
        cards?:
          | T
          | {
              itemKey?: T;
              title?: T;
              description?: T;
              image?: T;
              legacyImagePath?: T;
              alt?: T;
              objectPosition?: T;
              id?: T;
            };
      };
  clubs?:
    | T
    | {
        flagship?:
          | T
          | {
              name?: T;
              tagline?: T;
              description?: T;
              image?: T;
              legacyImagePath?: T;
              alt?: T;
            };
        cards?:
          | T
          | {
              itemKey?: T;
              title?: T;
              description?: T;
              image?: T;
              legacyImagePath?: T;
              alt?: T;
              objectPosition?: T;
              id?: T;
            };
      };
  contact?:
    | T
    | {
        eyebrow?: T;
        description?: T;
        address?: T;
        phoneDisplay?: T;
        phoneHref?: T;
        admissionsEmail?: T;
        principalEmail?: T;
        mapEmbedUrl?: T;
        mapTitle?: T;
        visitTitle?: T;
        visitDescription?: T;
        ctaLabel?: T;
        ctaHref?: T;
      };
  publicationState?: T;
  publishAt?: T;
  expiresAt?: T;
  publishedAt?: T;
  publicationActor?: T;
  publicationChangedAt?: T;
  createdBy?: T;
  assignedEditors?: T;
  migrationId?: T;
  migrationSource?: T;
  migrationFingerprint?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "editorial_select".
 */
export interface EditorialSelect<T extends boolean = true> {
  kind?: T;
  title?: T;
  slug?: T;
  publicPathKey?: T;
  summary?: T;
  body?: T;
  message?: T;
  link?: T;
  displayOrder?: T;
  priority?: T;
  placements?: T;
  category?: T;
  featured?: T;
  displayDate?: T;
  image?: T;
  legacyImagePath?: T;
  startsAt?: T;
  endsAt?: T;
  location?: T;
  publicationState?: T;
  publishAt?: T;
  expiresAt?: T;
  publishedAt?: T;
  publicationActor?: T;
  publicationChangedAt?: T;
  createdBy?: T;
  assignedEditors?: T;
  migrationId?: T;
  migrationSource?: T;
  migrationFingerprint?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  category?: T;
  academicYear?: T;
  effectiveDate?: T;
  description?: T;
  issueNumber?: T;
  audience?: T;
  displayOrder?: T;
  placements?: T;
  sourceType?: T;
  pdf?: T;
  externalUrl?: T;
  legacyExternalUrl?: T;
  publicationState?: T;
  publishAt?: T;
  expiresAt?: T;
  publishedAt?: T;
  publicationActor?: T;
  publicationChangedAt?: T;
  createdBy?: T;
  assignedEditors?: T;
  migrationId?: T;
  migrationSource?: T;
  migrationFingerprint?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  referenceCode?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-deliveries_select".
 */
export interface NotificationDeliveriesSelect<T extends boolean = true> {
  channel?: T;
  sourceType?: T;
  source?: T;
  status?: T;
  attemptNumber?: T;
  attemptedAt?: T;
  recipient?: T;
  providerMessageId?: T;
  errorCode?: T;
  errorMessage?: T;
  initiatedBy?: T;
  previousAttempt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-records_select".
 */
export interface AuditRecordsSelect<T extends boolean = true> {
  actorType?: T;
  actorId?: T;
  actorRole?: T;
  action?: T;
  targetCollection?: T;
  targetId?: T;
  occurredAt?: T;
  outcome?: T;
  metadata?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Control the announcement bar and choose which reviewed CMS areas are live on the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "website-settings".
 */
export interface WebsiteSetting {
  id: number;
  announcementBar: {
    enabled: boolean;
    speed: 'slow' | 'normal' | 'fast';
    theme: 'teal' | 'navy' | 'maroon';
  };
  /**
   * Keep existing content, add CMS content alongside it, or replace it after migrated drafts have been reviewed and published.
   */
  contentSources: {
    resourcesNews: 'legacy' | 'append' | 'managed';
    resourcesAnnouncements: 'legacy' | 'append' | 'managed';
    resourcesDownloads: 'legacy' | 'append' | 'managed';
    schoolCalendar: 'legacy' | 'append' | 'managed';
    mandatoryDisclosure: 'legacy' | 'append' | 'managed';
    sports: 'legacy' | 'append' | 'managed';
    clubs: 'legacy' | 'append' | 'managed';
    contact: 'legacy' | 'append' | 'managed';
    homepageNews: 'legacy' | 'append' | 'managed';
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Configure non-secret email recipients and notification enablement.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-settings".
 */
export interface NotificationSetting {
  id: number;
  admissionEnabled: boolean;
  admissionRecipient?: string | null;
  defaultFormEnabled: boolean;
  defaultFormRecipient?: string | null;
  formOverrides?:
    | {
        form: number | Form;
        enabled: boolean;
        recipient?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "website-settings_select".
 */
export interface WebsiteSettingsSelect<T extends boolean = true> {
  announcementBar?:
    | T
    | {
        enabled?: T;
        speed?: T;
        theme?: T;
      };
  contentSources?:
    | T
    | {
        resourcesNews?: T;
        resourcesAnnouncements?: T;
        resourcesDownloads?: T;
        schoolCalendar?: T;
        mandatoryDisclosure?: T;
        sports?: T;
        clubs?: T;
        contact?: T;
        homepageNews?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-settings_select".
 */
export interface NotificationSettingsSelect<T extends boolean = true> {
  admissionEnabled?: T;
  admissionRecipient?: T;
  defaultFormEnabled?: T;
  defaultFormRecipient?: T;
  formOverrides?:
    | T
    | {
        form?: T;
        enabled?: T;
        recipient?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}